#diff_derive go_to_goal node 
KP: 9
KA: 12
KB: -3
rate: 50
forwardMovementOnly: True
max_linear_speed: 0.1
min_linear_speed: -0.1
max_angular_speed: 0.1
min_angular_speed: -0.1

linear_tolerance: 0.1
angular_tolerance: 0.02
max_linear_acceleration: 0.1
max_angular_acceleration: 0.01
